[build]
# ignore = "echo $CACHED_COMMIT_REF && echo $COMMIT_REF && git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."
  ignore = "exit 1"
  command = "echo $CACHED_COMMIT_REF && echo $COMMIT_REF"
  base = "packages/site2"
  publish = "out"
  functions = "serverless"