name: Enforce Draft PR

on:
  pull_request:
    types: [opened, reopened]
    branches: [ develop, main ]

jobs:
  Set-Draft:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && !github.event.pull_request.draft
    steps:
      - name: Mark as draft
        uses: voiceflow/draft-pr@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
