# End Tests
# Matrix of options calling reusable workflow?

name: End

on:
  workflow_dispath:
  pull_request:
    branches: [ develop, main ]
    types: [opened, reopened, synchronize, ready_for_review]

env:
  COMMIT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
  BRANCH: ${{ github.event_name == 'pull_request' && format('refs/heads/{0}', github.event.pull_request.head.ref) || github.ref }}

concurrency:
  group: ci-tests-${{ env.BRANCH }}-1
  cancel-in-progress: true

jobs:
  isActivePR:
    uses: ./.github/workflows/active-pr-check.yml

  # This job will not run if the isActivePR failed or if its "activePR" output is "false"
  Tests:
    runs-on: ubuntu-latest
    needs: [isActivePR]
    if: needs.isActivePR.outputs.activePR == 'true'
    steps:
      - name: show branch and commit
      - id: as
      - run: echo 'Branch: ${{ env.BRANCH }}, COMMIT: ${{ env.COMMIT_SHA }}'
      
      