# End Tests
# Matrix of options calling reusable workflow?

name: End

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches: [ develop, main ]

env:
  COMMIT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
  BRANCH: ${{ github.event_name == 'pull_request' && format('refs/heads/{0}', github.event.pull_request.head.ref) || github.ref }}

concurrency:
  group: ci-tests-${{ github.event_name == 'pull_request' && format('refs/heads/{0}', github.event.pull_request.head.ref) || github.ref }}-1
  cancel-in-progress: true

jobs:
  # isActivePR:
  #   uses: ./.github/workflows/active-pr-check.yml

  # This job will not run if the isActivePR failed or if its "activePR" output is "false"
  Tests:
    runs-on: ubuntu-latest
    # needs: [isActivePR]
    # github.event_name == 'pull_request' && !github.event.pull_request.draft
    # if: needs.isActivePR.outputs.activePR == 'true'
    if: github.event_name == 'pull_request' && !github.event.pull_request.draft
    steps:
      - name: show branch and commit
        id: show-branch-commit
        run: "echo 'Active PR and Branch: ${{ env.BRANCH }}, COMMIT: ${{ env.COMMIT_SHA }}'"

  NoTests:
    runs-on: ubuntu-latest
    # needs: [isActivePR]
    # if: needs.isActivePR.outputs.activePR == 'false'
    if: github.event_name != 'pull_request' || github.event.pull_request.draft
    steps:
      - name: show branch and commit
        id: show-branch-commit
        run: "echo 'No Active PR Branch: ${{ env.BRANCH }}, COMMIT: ${{ env.COMMIT_SHA }}'"
      